-- Supervised Crime Analysis Model
-- CREATE TABLES

CREATE TABLE Jan8_TX_data_for_ML (
	INCIDENT_MONTH VARCHAR NOT NULL,
	INCIDENT_HOUR VARCHAR NOT NULL,
    ARR_AGE_NUM VARCHAR NOT NULL,
    ARR_SEX_CODE VARCHAR NOT NULL,
    ARR_RACE_ID VARCHAR NOT NULL,
    ARR_RESIDENT_CODE VARCHAR NOT NULL,
    LOCATION_ID VARCHAR NOT NULL,
    SUSPECT_USING_ID VARCHAR NOT NULL,
    AGENCY_TYPE_NAME VARCHAR NOT NULL,
    POPULATION VARCHAR NOT NULL,
    SUBURBAN_AREA_FLAG VARCHAR NOT NULL,
    TOTAL_EMPLOYEES VARCHAR,
    OFFENSE_TYPE_ID VARCHAR NOT NULL,
    AGENCY_ID VARCHAR NOT NULL,
    CRIME_AGAINST VARCHAR NOT NULL,
    FOREIGN KEY (ARR_RACE_ID) REFERENCES final_REF_RACE (RACE_ID)  
);

CREATE TABLE final_REF_RACE (
    RACE_ID VARCHAR NOT NULL,
    RACE_CODE VARCHAR NOT NULL,
    RACE_DESC VARCHAR NOT NULL,
    SORT_ORDER VARCHAR NOT NULL,
    START_YEAR VARCHAR,
    END_YEAR VARCHAR,
    NOTES VARCHAR,
    PRIMARY KEY (RACE_ID)
);


-- JOIN TABLES

SELECT DISTINCT j.ARR_RACE_ID, f.RACE_DESC
FROM Jan8_TX_data_for_ML AS j
LEFT JOIN  final_REF_RACE AS f
ON f.RACE_ID = j.ARR_RACE_ID
ORDER BY j.ARR_RACE_ID;

