-- Table: public.texas_2020

CREATE TABLE texas_2020(
	AGENCY_ID INT NOT NULL,
    INCIDENT_ID INT NOT NULL,
    INCIDENT_DATE DATE NOT NULL,
    INCIDENT_HOUR INT NOT NULL,
    CLEARED_EXCEPT_ID INT NOT NULL,
    OFFENSE_ID INT NOT NULL,
    OFFENSE_TYPE_ID INT NOT NULL,
    PUB_AGENCY_NAME VARCHAR NOT NULL,
    AGENCY_TYPE_NAME VARCHAR NOT NULL,
    POPULATION INT NOT NULL,
    SUBURBAN_AREA_FLAG VARCHAR NOT NULL,
    POPULATION_GROUP_CODE INT NOT NULL,
    COUNTY_NAME VARCHAR NOT NULL,
    OFFENSE_CODE VARCHAR NOT NULL,
    OFFENSE_NAME VARCHAR NOT NULL,
    CRIME_AGAINST VARCHAR NOT NULL,
    OFFENSE_CATEGORY_NAME VARCHAR NOT NULL,
    OFFENSE_GROUP VARCHAR NOT NULL,
    PRIMARY KEY (INCIDENT_ID)
);

CREATE TABLE texas_2019(
	AGENCY_ID INT NOT NULL,
    INCIDENT_ID INT NOT NULL,
    INCIDENT_DATE DATE NOT NULL,
    INCIDENT_HOUR INT NOT NULL,
    CLEARED_EXCEPT_ID INT NOT NULL,
    OFFENSE_ID INT NOT NULL,
    OFFENSE_TYPE_ID INT NOT NULL,
    PUB_AGENCY_NAME VARCHAR NOT NULL,
    AGENCY_TYPE_NAME VARCHAR NOT NULL,
    POPULATION INT NOT NULL,
    SUBURBAN_AREA_FLAG VARCHAR NOT NULL,
    POPULATION_GROUP_CODE INT NOT NULL,
    COUNTY_NAME VARCHAR NOT NULL,
    OFFENSE_CODE VARCHAR NOT NULL,
    OFFENSE_NAME VARCHAR NOT NULL,
    CRIME_AGAINST VARCHAR NOT NULL,
    OFFENSE_CATEGORY_NAME VARCHAR NOT NULL,
    OFFENSE_GROUP VARCHAR NOT NULL,
    PRIMARY KEY (INCIDENT_ID)
);

CREATE TABLE texas_2018(
	AGENCY_ID INT NOT NULL,
    INCIDENT_ID INT NOT NULL,
    INCIDENT_DATE DATE NOT NULL,
    INCIDENT_HOUR INT NOT NULL,
    CLEARED_EXCEPT_ID INT NOT NULL,
    OFFENSE_ID INT NOT NULL,
    OFFENSE_TYPE_ID INT NOT NULL,
    PUB_AGENCY_NAME VARCHAR NOT NULL,
    AGENCY_TYPE_NAME VARCHAR NOT NULL,
    POPULATION INT NOT NULL,
    SUBURBAN_AREA_FLAG VARCHAR NOT NULL,
    POPULATION_GROUP_CODE INT NOT NULL,
    COUNTY_NAME VARCHAR NOT NULL,
    OFFENSE_CODE VARCHAR NOT NULL,
    OFFENSE_NAME VARCHAR NOT NULL,
    CRIME_AGAINST VARCHAR NOT NULL,
    OFFENSE_CATEGORY_NAME VARCHAR NOT NULL,
    OFFENSE_GROUP VARCHAR NOT NULL,
    PRIMARY KEY (INCIDENT_ID)
);

CREATE TABLE texas_2017(
	AGENCY_ID INT NOT NULL,
    INCIDENT_ID INT NOT NULL,
    INCIDENT_DATE DATE NOT NULL,
    INCIDENT_HOUR INT NOT NULL,
    CLEARED_EXCEPT_ID INT NOT NULL,
    OFFENSE_ID INT NOT NULL,
    OFFENSE_TYPE_ID INT NOT NULL,
    PUB_AGENCY_NAME VARCHAR NOT NULL,
    AGENCY_TYPE_NAME VARCHAR NOT NULL,
    POPULATION INT NOT NULL,
    SUBURBAN_AREA_FLAG VARCHAR NOT NULL,
    POPULATION_GROUP_CODE INT NOT NULL,
    COUNTY_NAME VARCHAR NOT NULL,
    OFFENSE_CODE VARCHAR NOT NULL,
    OFFENSE_NAME VARCHAR NOT NULL,
    CRIME_AGAINST VARCHAR NOT NULL,
    OFFENSE_CATEGORY_NAME VARCHAR NOT NULL,
    OFFENSE_GROUP VARCHAR NOT NULL,
    PRIMARY KEY (INCIDENT_ID)
);

